global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-api'
    static_configs:
      - targets: ['localhost:9091']
        labels:
          job: user-api
          app: user-api
          env: dev
          instance: 127.0.0.1:8000
  - job_name: 'user-rpc'
    static_configs:
      - targets: ['localhost:9092']
        labels:
          job: user-rpc
          app: user-rpc
          env: dev
          instance: 127.0.0.1:9100
