// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package usercenter

import (
	"context"

	"zero-demo/user-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProjectReq   = pb.GetProjectReq
	GetUserInfoReq  = pb.GetUserInfoReq
	GetUserInfoResp = pb.GetUserInfoResp
	ProjectResp     = pb.ProjectResp

	Usercenter interface {
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetProjectInfo(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*ProjectResp, error)
		GetProjectInfoByProKey(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*ProjectResp, error)
	}

	defaultUsercenter struct {
		cli zrpc.Client
	}
)

func NewUsercenter(cli zrpc.Client) Usercenter {
	return &defaultUsercenter{
		cli: cli,
	}
}

func (m *defaultUsercenter) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUsercenter) GetProjectInfo(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*ProjectResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.GetProjectInfo(ctx, in, opts...)
}

func (m *defaultUsercenter) GetProjectInfoByProKey(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*ProjectResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.GetProjectInfoByProKey(ctx, in, opts...)
}
