// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserId int64 `json:"userId"`
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type ProjectInfoReq struct {
	ProKey string `json:"proKey"`
}

type ProjectInfoResp struct {
	AccessKey    string `json:"access_key"`
	AccessSecret string `json:"access_secret"`
	CreateAt     string `json:"create_at"`
	Name         string `json:"name"`
	Status       int    `json:"status"`
	Types        string `json:"types"`
}
